# Generated by Django 4.2.6 on 2023-10-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegexQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.TextField()),
                ('regex_pattern', models.CharField(max_length=255)),
            ],
        ),
    ]
